// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afvpruijyksfkawhagcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdnBydWlqeWtzZmthd2hhZ2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTE2MTEsImV4cCI6MjA2MjQ2NzYxMX0.mfqGQoLo2h1AeYlQwra84dziOahYMcOgTvYTgcspnj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);